### ISSUE TITLE
The URL filter doesn't work for all valid YouTube URLs

### ISSUE THREAD

**Issue by keiwando** [karmdesai/hyde#1]
Thanks for writing this extension!

After first installing it, I couldn't get it to work until I looked at the source code. The URL of the video I was watching looked like

`youtube.com/watch?reload=9&v=...`

so it wasn't being recognized as a youtube video by the filter here:
https://github.com/karmdesai/hyde/blob/0b1852b3629824015f588a1de3351295f8357f0f/src/background.js#L11

The url parameters on YouTube are not order sensitive so the regex should allow for other parameters to appear before the video id.

**Comment by karmdesai** [comment]
Hi @keiwando, this seems like a simple fix. I will try to get it done and update the Chrome extension within a few days. Thanks for your help!

**Comment by karmdesai** [comment]
Hi @keiwando, I have fixed the issue in the latest version (1.1). It works on my end, please let me know if it works for you (you might have to update the extension if it is not done automatically).

**Comment by keiwando** [comment]
Yes, it works for me too. Thanks!
